### ISSUE TITLE
文件都少上传了还是咋地了

### ISSUE THREAD

**Issue by xiaozhi805157387** [QiaoBug/hexo-theme-quiet#1]
文件都少上传了还是咋地了

**Comment by 79zhanghao** [comment]
？我没有明白您的意思你能在描述下什么问题吗？

**Comment by 79zhanghao** [comment]
> 文件都少上传了还是咋地了
？我没有明白您的意思你能在描述下什么问题吗？

**Comment by xiaozhi805157387** [comment]
Duplicate of # 打开您的网页想查看一下效果.发现css没加载.

**Comment by 79zhanghao** [comment]
> Duplicate of # 打开您的网页想查看一下效果.发现css没加载.
您可以清理下缓存在尝试一下
